---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/raohwork/marionette-go

steps:
- name: test-go1.10.8-fx66.0b9
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./. -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnsender -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnclient -benchmem -cover
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 66.0b9
    GO_VER: 1.10.8
  volumes:
  - name: opt
    path: /opt

- name: test-go1.10.8-fx66.0b12
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./. -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnsender -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnclient -benchmem -cover
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 66.0b12
    GO_VER: 1.10.8
  volumes:
  - name: opt
    path: /opt

- name: test-go1.11.5-fx66.0b9
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./. -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnsender -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnclient -benchmem -cover
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 66.0b9
    GO_VER: 1.11.5
  volumes:
  - name: opt
    path: /opt

- name: test-go1.11.5-fx66.0b12
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./. -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnsender -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnclient -benchmem -cover
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 66.0b12
    GO_VER: 1.11.5
  volumes:
  - name: opt
    path: /opt

- name: test-go1.12-fx66.0b9
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./. -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnsender -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnclient -benchmem -cover
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 66.0b9
    GO_VER: 1.12
  volumes:
  - name: opt
    path: /opt

- name: test-go1.12-fx66.0b12
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./. -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnsender -benchmem -cover
  - run-test.sh go test -p 2 -bench ./mnclient -benchmem -cover
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 66.0b12
    GO_VER: 1.12
  volumes:
  - name: opt
    path: /opt

- name: test-tabmgr-go1.10.8-fx64.0
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 64.0
    GO_VER: 1.10.8
  volumes:
  - name: opt
    path: /opt

- name: test-tabmgr-go1.10.8-fx65.0
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 65.0
    GO_VER: 1.10.8
  volumes:
  - name: opt
    path: /opt

- name: test-tabmgr-go1.11.5-fx64.0
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 64.0
    GO_VER: 1.11.5
  volumes:
  - name: opt
    path: /opt

- name: test-tabmgr-go1.11.5-fx65.0
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 65.0
    GO_VER: 1.11.5
  volumes:
  - name: opt
    path: /opt

- name: test-tabmgr-go1.12-fx64.0
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 64.0
    GO_VER: 1.12
  volumes:
  - name: opt
    path: /opt

- name: test-tabmgr-go1.12-fx65.0
  image: ronmi/go-firefox
  commands:
  - run-test.sh go test -p 2 -bench ./tabmgr -benchmem -cover
  environment:
    FX_VER: 65.0
    GO_VER: 1.12
  volumes:
  - name: opt
    path: /opt

volumes:
- name: opt
  temp:
    size_limit: 5GiB

...
